version: "3.8"

x-environment-common: &environment-common
  HOST: 0.0.0.0
  NODE_ENV: development

x-node-common: &node-common
  build: .
  image: tracktick-challange
  stdin_open: true
  env_file:
    - .env.dev
  environment:
    HOST: 0.0.0.0
    NODE_ENV: development
  volumes:
    - .:/app

services:
  app:
    <<: *node-common
    environment: *environment-common
    ports:
      - 3000:3000
    command: >
      bash -c "
        yarn install &&
        yarn start"

  app-local:
    <<: *node-common
    environment:
      <<: *environment-common
      REACT_APP_TRACKTIK_HOST: http://localhost:3001
    ports:
      - 3000:3000
    depends_on:
      - json-server
    command: >
      bash -c "
        yarn install &&
        yarn start"

  json-server:
    <<: *node-common
    environment: *environment-common
    ports:
      - 3001:3001
    command: >
      bash -c "
        yarn install &&
        yarn json-server"

  storybook:
    <<: *node-common
    environment: *environment-common
    ports:
      - 6006:6006
    command: >
      bash -c "
        yarn install &&
        yarn storybook"
