export const SITES_JSON_MOCK = [
  {
    id: "h8ZUHSsZ_A",
    clientId: "HYm3QIXsbAQYL",
    title: "Electronics HQ",
    createdAt: "Fri Dec 07 2018 02:15:07 GMT-0500 (EST)",
    updatedAt: "Tue Jul 16 2019 10:18:01 GMT-0400 (EDT)",
    contacts: {
      main: {
        id: "XPp7oyJRmz",
        firstName: "Hugh",
        lastName: "Windler",
        email: "Aurelio.Goyette@yahoo.com",
        phoneNumber: "533.880.9306 x0425",
        jobTitle: "National Applications Planner",
        address: {
          zipCode: "25048",
          city: "New Gwen",
          street: "63833 Alexys Gateway",
          country: "Kenya",
          state: "Texas",
        },
      },
    },
    address: {
      zipCode: "74881-2911",
      city: "Lakinchester",
      street: "611 Miller Glen",
      country: "France",
      state: "Illinois",
    },
    images: [
      "http://lorempixel.com/640/480/city",
      "http://lorempixel.com/640/480/city",
    ],
    tags: ["renovated", "company"],
  },
  {
    id: "Ki16O2yms_",
    clientId: "HYm3QIXsbAQYL",
    title: "Health Garage",
    createdAt: "Mon Oct 29 2018 22:04:34 GMT-0400 (EDT)",
    updatedAt: "Mon Jul 15 2019 16:44:04 GMT-0400 (EDT)",
    contacts: {
      main: {
        id: "yI1wXCKtBH",
        firstName: "Garret",
        lastName: "Koss",
        email: "Abner.McClure@yahoo.com",
        phoneNumber: "776-098-5513 x53648",
        jobTitle: "Central Directives Representative",
        address: {
          zipCode: "91231-2824",
          city: "Hintzchester",
          street: "11359 Edd Throughway",
          country: "Germany",
          state: "New York",
        },
      },
    },
    address: {
      zipCode: "60068-9134",
      city: "East Zaneview",
      street: "79324 Ernie Gardens",
      country: "Western Sahara",
      state: "Colorado",
    },
    images: [
      "http://lorempixel.com/640/480/city",
      "http://lorempixel.com/640/480/city",
      "http://lorempixel.com/640/480/city",
      "http://lorempixel.com/640/480/city",
    ],
    tags: ["new", "company"],
  },
];
